FROM python:3.11-slim

WORKDIR /app

COPY requirements-core.txt .
RUN pip install --no-cache-dir -r requirements-core.txt

COPY . .

CMD ["celery", "-A", "app.celery_app", "worker", "--loglevel=info", "--pool=solo"]